# Generated by Django 5.1.4 on 2025-02-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_viktoryna', '0005_remove_question_time_limit_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
